export const currencies = [
    { "label": "United States Dollar", "value": "USD" },
    { "label": "Euro", "value": "EUR" },
    { "label": "British Pound Sterling", "value": "GBP" },
    { "label": "Japanese Yen", "value": "JPY" },
    { "label": "Swiss Franc", "value": "CHF" },
    { "label": "Canadian Dollar", "value": "CAD" },
    { "label": "Australian Dollar", "value": "AUD" },
    { "label": "New Zealand Dollar", "value": "NZD" },
    { "label": "Chinese Yuan Renminbi", "value": "CNY" },
    { "label": "Indian Rupee", "value": "INR" },
    { "label": "Mexican Peso", "value": "MXN" },
    { "label": "Brazilian Real", "value": "BRL" },
    { "label": "South African Rand", "value": "ZAR" },
    { "label": "Russian Ruble", "value": "RUB" },
    { "label": "Hong Kong Dollar", "value": "HKD" },
    { "label": "Singapore Dollar", "value": "SGD" },
    { "label": "South Korean Won", "value": "KRW" },
    { "label": "Turkish Lira", "value": "TRY" },
    { "label": "Indonesian Rupiah", "value": "IDR" },
    { "label": "Malaysian Ringgit", "value": "MYR" },
    { "label": "Thai Baht", "value": "THB" },
    { "label": "Norwegian Krone", "value": "NOK" },
    { "label": "Swedish Krona", "value": "SEK" },
    { "label": "Danish Krone", "value": "DKK" },
    { "label": "Polish Zloty", "value": "PLN" },
    { "label": "Israeli New Shekel", "value": "ILS" },
    { "label": "Saudi Riyal", "value": "SAR" },
    { "label": "United Arab Emirates Dirham", "value": "AED" },
    { "label": "Egyptian Pound", "value": "EGP" },
    { "label": "Pakistani Rupee", "value": "PKR" },
    { "label": "Chilean Peso", "value": "CLP" },
    { "label": "Colombian Peso", "value": "COP" },
    { "label": "Philippine Peso", "value": "PHP" },
    { "label": "Czech Koruna", "value": "CZK" },
    { "label": "Hungarian Forint", "value": "HUF" },
    { "label": "Icelandic Krona", "value": "ISK" },
    { "label": "Romanian Leu", "value": "RON" },
    { "label": "Kuwaiti Dinar", "value": "KWD" },
    { "label": "Qatari Riyal", "value": "QAR" },
    { "label": "Omani Rial", "value": "OMR" },
    { "label": "Jordanian Dinar", "value": "JOD" },
    { "label": "Bahraini Dinar", "value": "BHD" },
    { "label": "Bangladeshi Taka", "value": "BDT" },
    { "label": "Sri Lankan Rupee", "value": "LKR" },
    { "label": "Vietnamese Dong", "value": "VND" },
    { "label": "Kazakhstani Tenge", "value": "KZT" },
    { "label": "Ukrainian Hryvnia", "value": "UAH" },
    { "label": "Kenyan Shilling", "value": "KES" },
    { "label": "Tanzanian Shilling", "value": "TZS" },
    { "label": "Ugandan Shilling", "value": "UGX" },
    { "label": "Ghanaian Cedi", "value": "GHS" },
    { "label": "Nigerian Naira", "value": "NGN" },
    { "label": "Algerian Dinar", "value": "DZD" },
    { "label": "Moroccan Dirham", "value": "MAD" },
    { "label": "Tunisian Dinar", "value": "TND" },
    { "label": "Libyan Dinar", "value": "LYD" },
    { "label": "Mauritian Rupee", "value": "MUR" },
    { "label": "Seychellois Rupee", "value": "SCR" },
    { "label": "Ethiopian Birr", "value": "ETB" },
    { "label": "Somali Shilling", "value": "SOS" },
    { "label": "Sudanese Pound", "value": "SDG" },
    { "label": "South Sudanese Pound", "value": "SSP" },
    { "label": "Zambian Kwacha", "value": "ZMW" },
    { "label": "Malawian Kwacha", "value": "MWK" },
    { "label": "Botswana Pula", "value": "BWP" },
    { "label": "Namibian Dollar", "value": "NAD" },
    { "label": "Lesotho Loti", "value": "LSL" },
    { "label": "Swazi Lilangeni", "value": "SZL" },
    { "label": "Mozambican Metical", "value": "MZN" },
    { "label": "Angolan Kwanza", "value": "AOA" },
    { "label": "Zimbabwean Dollar", "value": "ZWL" },
    { "label": "Georgian Lari", "value": "GEL" },
    { "label": "Armenian Dram", "value": "AMD" },
    { "label": "Azerbaijani Manat", "value": "AZN" },
    { "label": "Turkmenistani Manat", "value": "TMT" },
    { "label": "Uzbekistani Som", "value": "UZS" },
    { "label": "Kyrgyzstani Som", "value": "KGS" },
    { "label": "Tajikistani Somoni", "value": "TJS" },
    { "label": "Mongolian Tugrik", "value": "MNT" },
    { "label": "Bhutanese Ngultrum", "value": "BTN" },
    { "label": "Nepalese Rupee", "value": "NPR" },
    { "label": "Maldivian Rufiyaa", "value": "MVR" },
    { "label": "Samoan Tala", "value": "WST" },
    { "label": "Tongan Paʻanga", "value": "TOP" },
    { "label": "Fijian Dollar", "value": "FJD" },
    { "label": "Papua New Guinean Kina", "value": "PGK" },
    { "label": "Vanuatu Vatu", "value": "VUV" },
    { "label": "Solomon Islands Dollar", "value": "SBD" },
    { "label": "New Caledonian Franc", "value": "XPF" },
    { "label": "Falkland Islands Pound", "value": "FKP" },
    { "label": "Gibraltar Pound", "value": "GIP" },
    { "label": "Saint Helena Pound", "value": "SHP" },
    { "label": "Jamaican Dollar", "value": "JMD" },
    { "label": "Barbadian Dollar", "value": "BBD" },
    { "label": "Bahamian Dollar", "value": "BSD" },
    { "label": "Trinidad and Tobago Dollar", "value": "TTD" },
    { "label": "Belize Dollar", "value": "BZD" },
    { "label": "Guyanaese Dollar", "value": "GYD" },
    { "label": "Haitian Gourde", "value": "HTG" },
    { "label": "Surinamese Dollar", "value": "SRD" }
  ]
  